<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
			'key' => 'group_5a04c8a3eb211-2',
			'title' => 'Clinic Home Page',
			'fields' => array(
					array(
							'key' => 'field_5a04c8d64b563',
							'label' => 'About Clinic Description',
							'name' => 'about_clinic_description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
					),
					array(
							'key' => 'field_5a04c93a4b564',
							'label' => 'Clinic Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
					),
					array(
							'key' => 'field_5a12fb81d45f0',
							'label' => 'Team Section',
							'name' => 'team_section',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
									array(
											'key' => 'field_5a12fbb9d45f2',
											'label' => 'Show About Team Section',
											'name' => 'show_about_team_section',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'ui' => 1,
											'ui_on_text' => '',
											'ui_off_text' => '',
									),
									array(
											'key' => 'field_5a12fb9bd45f1',
											'label' => 'About Team Description',
											'name' => 'about_team_description',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
													array(
															array(
																	'field' => 'field_5a12fbb9d45f2',
																	'operator' => '==',
																	'value' => '1',
															),
													),
											),
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => '',
											'new_lines' => 'wpautop',
									),
									array(
											'key' => 'field_5a12fbded45f3',
											'label' => 'Show About Page Button',
											'name' => 'show_about_page_button',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
													array(
															array(
																	'field' => 'field_5a12fbb9d45f2',
																	'operator' => '==',
																	'value' => '1',
															),
													),
											),
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'message' => '',
											'default_value' => 1,
											'ui' => 1,
											'ui_on_text' => '',
											'ui_off_text' => '',
									),
							),
					),
					array(
							'key' => 'field_5a04c95e4b565',
							'label' => 'Services & Benefits',
							'name' => 'services_benefits',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Service/Benefit',
							'sub_fields' => array(
									array(
											'key' => 'field_5a04c97b4b566',
											'label' => 'Service/Benefit Title',
											'name' => 'title',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
									),
									array(
											'key' => 'field_5a04c9824b567',
											'label' => 'Service/Benefit Description',
											'name' => 'description',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => '',
											'new_lines' => 'wpautop',
									),
									array(
											'key' => 'field_5a04c99c4b568',
											'label' => 'Service/Benefit Description Point Form Area',
											'name' => 'description_points_area',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => 'Add Point',
											'sub_fields' => array(
													array(
															'key' => 'field_5a04c9a64b569',
															'label' => 'Description Points',
															'name' => 'description_point',
															'type' => 'text',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
													),
											),
									),
									array(
											'key' => 'field_5a04c9b84b56a',
											'label' => 'Service/Benefit Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'return_format' => 'array',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
									),
									array(
											'key' => 'field_5a04c9cc4b56b',
											'label' => 'Show "Request Appointment" button',
											'name' => 'show_request_appointment_button',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'ui' => 1,
											'ui_on_text' => '',
											'ui_off_text' => '',
									),
							),
					),
					array(
							'key' => 'field_5a74d0f8e8894',
							'label' => 'Custom Get Directions Link',
							'name' => 'google_maps_direction',
							'type' => 'url',
							'instructions' => 'This can be left empty in most cases. Use this if Google\'s default pin position is incorrect for the Get Directions link. Example: https://www.google.com/maps?daddr=331+Queens+Ave+London+ON+N6B+1X2+CA',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
					),
			),
			array(
	'key' => 'field_5d0bcf69d4dc1',
	'label' => 'Request An Appointment Form ID',
	'name' => 'appointment_id',
	'type' => 'number',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'default_value' => '',
	'placeholder' => '',
	'prepend' => '',
	'append' => '',
	'min' => '',
	'max' => '',
	'step' => '',
),
),
			'location' => array(
					array(
							array(
									'param' => 'options_page',
									'operator' => '==',
									'value' => 'clinic-home-page-options',
							),
					),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'custom_fields',
					4 => 'discussion',
					5 => 'comments',
					6 => 'format',
					7 => 'featured_image',
					8 => 'categories',
					9 => 'tags',
					10 => 'send-trackbacks',
			),
			'active' => 1,
			'description' => '',
	));
