<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c48ca9769174',
	'title' => 'Site Options',
	'fields' => array(
		array(
			'key' => 'field_5c48caa1b2b72',
			'label' => 'Site Region Selection',
			'name' => 'site_option_region_selection',
			'type' => 'checkbox',
			'instructions' => 'Select the country and region this site belongs to.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c48cb057ab9f',
			'label' => 'Shopify Affiliate ID',
			'name' => 'affiliate_id',
			'type' => 'text',
			'instructions' => 'Type in the Shopify Affiliate ID below for this clinic. To find out what the affiliate ID is, please visit <a href="https://store.maxliving.com/admin" target="_blank">https://store.maxliving.com/admin</a><br><br>Note: Make sure you only enter affiliate ID after the equal sign - https://store.maxliving.com/?srrf=<strong>AFFILIATEID</strong>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c8924b975bdf',
			'label' => 'Homecare Certification',
			'name' => 'homecare_cert',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c89484d85592',
			'label' => 'Homecare Certification Level 1',
			'name' => 'homecare_cert_lvl1',
			'type' => 'true_false',
			'instructions' => '<strong>Requires:</strong> Homecare Certification',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c8924b975bdf',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c89486e85593',
			'label' => 'Homecare Certification Level 2',
			'name' => 'homecare_cert_lvl2',
			'type' => 'true_false',
			'instructions' => '<strong>Requires:</strong> Homecare Certification Level 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c89484d85592',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c8948ab85594',
			'label' => 'Nutrition Certification',
			'name' => 'nutrition_cert',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c8948e085596',
			'label' => 'Nutrition Certification Level 1',
			'name' => 'nutrition_cert_lvl1',
			'type' => 'true_false',
			'instructions' => '<strong>Requires:</strong> Nutrition Certification',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c8948ab85594',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c8948ee85597',
			'label' => 'Nutrition Certification Level 2',
			'name' => 'nutrition_cert_lvl2',
			'type' => 'true_false',
			'instructions' => '<strong>Requires:</strong> Nutrition Certification Level 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c8948e085596',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'clinic-site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
