<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "MaxLiving",
  "legalName" : "MaxLiving",
  "url": "https://maxliving.com",
  "logo" : "https://maxliving.com/themes/ml_core/images/ML-extended-logo.svg",
  "foundingDate" : "1998",
 "address": {
 "@type": "PostalAddress",
 "streetAddress": "4700 Millenia Blvd Suite 220 ",
 "addressLocality": "Orlando",
 "addressRegion": "Florida",
 "postalCode": "32839",
 "addressCountry": "United States"
 },
 "contactPoint": {
 "@type": "ContactPoint",
 "contactType": "customer support",
 "telephone": "[+1-321-939-3060]"
 },
 "sameAs": [
 "https://www.facebook.com/maxliving",
 "https://twitter.com/Max_Living",
 "https://www.instagram.com/maxlivingofficial",
 "https://www.linkedin.com/company/maxliving"
 ]}
</script>
